CITIES = {
    "auburn": "https://auburn.craigslist.org/search/",
    "birmingham": "https://bham.craigslist.org/search/",
    "dothan": "https://dothan.craigslist.org/search/",
    "florence / muscle shoals": "https://shoals.craigslist.org/search/",
    "gadsden-anniston": "https://gadsden.craigslist.org/search/",
    "huntsville / decatur": "https://huntsville.craigslist.org/search/",
    "mobile": "https://mobile.craigslist.org/search/",
    "montgomery": "https://montgomery.craigslist.org/search/",
    "tuscaloosa": "https://tuscaloosa.craigslist.org/search/",
    "anchorage / mat-su": "https://anchorage.craigslist.org/search/",
    "fairbanks": "https://fairbanks.craigslist.org/search/",
    "kenai peninsula": "https://kenai.craigslist.org/search/",
    "southeast alaska": "https://juneau.craigslist.org/search/",
    "flagstaff / sedona": "https://flagstaff.craigslist.org/search/",
    "mohave county": "https://mohave.craigslist.org/search/",
    "phoenix": "https://phoenix.craigslist.org/search/",
    "prescott": "https://prescott.craigslist.org/search/",
    "show low": "https://showlow.craigslist.org/search/",
    "sierra vista": "https://sierravista.craigslist.org/search/",
    "tucson": "https://tucson.craigslist.org/search/",
    "yuma": "https://yuma.craigslist.org/search/",
    "fayetteville": "https://fayetteville.craigslist.org/search/",
    "fort smith": "https://fortsmith.craigslist.org/search/",
    "jonesboro": "https://jonesboro.craigslist.org/search/",
    "little rock": "https://littlerock.craigslist.org/search/",
    "texarkana": "https://texarkana.craigslist.org/search/",
    "bakersfield": "https://bakersfield.craigslist.org/search/",
    "chico": "https://chico.craigslist.org/search/",
    "fresno / madera": "https://fresno.craigslist.org/search/",
    "gold country": "https://goldcountry.craigslist.org/search/",
    "hanford-corcoran": "https://hanford.craigslist.org/search/",
    "humboldt county": "https://humboldt.craigslist.org/search/",
    "imperial county": "https://imperial.craigslist.org/search/",
    "inland empire": "https://inlandempire.craigslist.org/search/",
    "los angeles": "https://losangeles.craigslist.org/search/",
    "mendocino county": "https://mendocino.craigslist.org/search/",
    "merced": "https://merced.craigslist.org/search/",
    "modesto": "https://modesto.craigslist.org/search/",
    "monterey bay": "https://monterey.craigslist.org/search/",
    "orange county": "https://orangecounty.craigslist.org/search/",
    "palm springs": "https://palmsprings.craigslist.org/search/",
    "redding": "https://redding.craigslist.org/search/",
    "sacramento": "https://sacramento.craigslist.org/search/",
    "san diego": "https://sandiego.craigslist.org/search/",
    "san francisco bay area": "https://sfbay.craigslist.org/search/",
    "san luis obispo": "https://slo.craigslist.org/search/",
    "santa barbara": "https://santabarbara.craigslist.org/search/",
    "santa maria": "https://santamaria.craigslist.org/search/",
    "siskiyou county": "https://siskiyou.craigslist.org/search/",
    "stockton": "https://stockton.craigslist.org/search/",
    "susanville": "https://susanville.craigslist.org/search/",
    "ventura county": "https://ventura.craigslist.org/search/",
    "visalia-tulare": "https://visalia.craigslist.org/search/",
    "yuba-sutter": "https://yubasutter.craigslist.org/search/",
    "boulder": "https://boulder.craigslist.org/search/",
    "colorado springs": "https://cosprings.craigslist.org/search/",
    "denver": "https://denver.craigslist.org/search/",
    "eastern CO": "https://eastco.craigslist.org/search/",
    "fort collins / north CO": "https://fortcollins.craigslist.org/search/",
    "high rockies": "https://rockies.craigslist.org/search/",
    "pueblo": "https://pueblo.craigslist.org/search/",
    "western slope": "https://westslope.craigslist.org/search/",
    "eastern CT": "https://newlondon.craigslist.org/search/",
    "hartford": "https://hartford.craigslist.org/search/",
    "new haven": "https://newhaven.craigslist.org/search/",
    "northwest CT": "https://nwct.craigslist.org/search/",
    "delaware": "https://delaware.craigslist.org/search/",
    "washington": "https://washingtondc.craigslist.org/search/",
    "broward county": "http://miami.craigslist.org/search//brw",
    "daytona beach": "https://daytona.craigslist.org/search/",
    "florida keys": "https://keys.craigslist.org/search/",
    "fort lauderdale": "https://fortlauderdale.craigslist.org/search/",
    "ft myers / SW florida": "https://fortmyers.craigslist.org/search/",
    "gainesville": "https://gainesville.craigslist.org/search/",
    "heartland florida": "https://cfl.craigslist.org/search/",
    "jacksonville": "https://onslow.craigslist.org/search/",
    "lakeland": "https://lakeland.craigslist.org/search/",
    "miami / dade": "http://miami.craigslist.org/search//mdc",
    "north central FL": "https://lakecity.craigslist.org/search/",
    "ocala": "https://ocala.craigslist.org/search/",
    "okaloosa / walton": "https://okaloosa.craigslist.org/search/",
    "orlando": "https://orlando.craigslist.org/search/",
    "panama city": "https://panamacity.craigslist.org/search/",
    "pensacola": "https://pensacola.craigslist.org/search/",
    "sarasota-bradenton": "https://sarasota.craigslist.org/search/",
    "south florida": "https://miami.craigslist.org/search/",
    "space coast": "https://spacecoast.craigslist.org/search/",
    "st augustine": "https://staugustine.craigslist.org/search/",
    "tallahassee": "https://tallahassee.craigslist.org/search/",
    "tampa bay area": "https://tampa.craigslist.org/search/",
    "treasure coast": "https://treasure.craigslist.org/search/",
    "palm beach county": "http://miami.craigslist.org/search//pbc",
    "albany": "https://albany.craigslist.org/search/",
    "athens": "https://athensohio.craigslist.org/search/",
    "atlanta": "https://atlanta.craigslist.org/search/",
    "augusta": "https://augusta.craigslist.org/search/",
    "brunswick": "https://brunswick.craigslist.org/search/",
    "columbus": "https://columbus.craigslist.org/search/",
    "macon / warner robins": "https://macon.craigslist.org/search/",
    "northwest GA": "https://nwga.craigslist.org/search/",
    "savannah / hinesville": "https://savannah.craigslist.org/search/",
    "statesboro": "https://statesboro.craigslist.org/search/",
    "valdosta": "https://valdosta.craigslist.org/search/",
    "hawaii": "https://honolulu.craigslist.org/search/",
    "boise": "https://boise.craigslist.org/search/",
    "east idaho": "https://eastidaho.craigslist.org/search/",
    "lewiston / clarkston": "https://lewiston.craigslist.org/search/",
    "twin falls": "https://twinfalls.craigslist.org/search/",
    "bloomington-normal": "https://bn.craigslist.org/search/",
    "champaign urbana": "https://chambana.craigslist.org/search/",
    "chicago": "https://chicago.craigslist.org/search/",
    "decatur": "https://decatur.craigslist.org/search/",
    "la salle co": "https://lasalle.craigslist.org/search/",
    "mattoon-charleston": "https://mattoon.craigslist.org/search/",
    "peoria": "https://peoria.craigslist.org/search/",
    "rockford": "https://rockford.craigslist.org/search/",
    "southern illinois": "https://carbondale.craigslist.org/search/",
    "springfield": "https://springfield.craigslist.org/search/",
    "western IL": "https://quincy.craigslist.org/search/",
    "bloomington": "https://bloomington.craigslist.org/search/",
    "evansville": "https://evansville.craigslist.org/search/",
    "fort wayne": "https://fortwayne.craigslist.org/search/",
    "indianapolis": "https://indianapolis.craigslist.org/search/",
    "kokomo": "https://kokomo.craigslist.org/search/",
    "lafayette / west lafayette": "https://tippecanoe.craigslist.org/search/",
    "muncie / anderson": "https://muncie.craigslist.org/search/",
    "richmond": "https://richmond.craigslist.org/search/",
    "south bend / michiana": "https://southbend.craigslist.org/search/",
    "terre haute": "https://terrehaute.craigslist.org/search/",
    "ames": "https://ames.craigslist.org/search/",
    "cedar rapids": "https://cedarrapids.craigslist.org/search/",
    "des moines": "https://desmoines.craigslist.org/search/",
    "dubuque": "https://dubuque.craigslist.org/search/",
    "fort dodge": "https://fortdodge.craigslist.org/search/",
    "iowa city": "https://iowacity.craigslist.org/search/",
    "mason city": "https://masoncity.craigslist.org/search/",
    "quad cities": "https://quadcities.craigslist.org/search/",
    "sioux city": "https://siouxcity.craigslist.org/search/",
    "southeast IA": "https://ottumwa.craigslist.org/search/",
    "waterloo / cedar falls": "https://waterloo.craigslist.org/search/",
    "lawrence": "https://lawrence.craigslist.org/search/",
    "manhattan": "https://ksu.craigslist.org/search/",
    "northwest KS": "https://nwks.craigslist.org/search/",
    "salina": "https://salina.craigslist.org/search/",
    "southeast KS": "https://seks.craigslist.org/search/",
    "southwest KS": "https://swks.craigslist.org/search/",
    "topeka": "https://topeka.craigslist.org/search/",
    "wichita": "https://wichita.craigslist.org/search/",
    "bowling green": "https://bgky.craigslist.org/search/",
    "eastern kentucky": "https://eastky.craigslist.org/search/",
    "lexington": "https://lexington.craigslist.org/search/",
    "louisville": "https://louisville.craigslist.org/search/",
    "owensboro": "https://owensboro.craigslist.org/search/",
    "western KY": "https://westky.craigslist.org/search/",
    "baton rouge": "https://batonrouge.craigslist.org/search/",
    "central louisiana": "https://cenla.craigslist.org/search/",
    "houma": "https://houma.craigslist.org/search/",
    "lafayette": "https://lafayette.craigslist.org/search/",
    "lake charles": "https://lakecharles.craigslist.org/search/",
    "monroe": "https://monroemi.craigslist.org/search/",
    "new orleans": "https://neworleans.craigslist.org/search/",
    "shreveport": "https://shreveport.craigslist.org/search/",
    "maine": "https://maine.craigslist.org/search/",
    "annapolis": "https://annapolis.craigslist.org/search/",
    "baltimore": "https://baltimore.craigslist.org/search/",
    "eastern shore": "https://easternshore.craigslist.org/search/",
    "frederick": "https://frederick.craigslist.org/search/",
    "southern maryland": "https://smd.craigslist.org/search/",
    "western maryland": "https://westmd.craigslist.org/search/",
    "boston": "https://boston.craigslist.org/search/",
    "cape cod / islands": "https://capecod.craigslist.org/search/",
    "south coast": "https://southcoast.craigslist.org/search/",
    "western massachusetts": "https://westernmass.craigslist.org/search/",
    "worcester / central MA": "https://worcester.craigslist.org/search/",
    "ann arbor": "https://annarbor.craigslist.org/search/",
    "battle creek": "https://battlecreek.craigslist.org/search/",
    "central michigan": "https://centralmich.craigslist.org/search/",
    "detroit metro": "https://detroit.craigslist.org/search/",
    "flint": "https://flint.craigslist.org/search/",
    "grand rapids": "https://grandrapids.craigslist.org/search/",
    "holland": "https://holland.craigslist.org/search/",
    "jackson": "https://jacksontn.craigslist.org/search/",
    "kalamazoo": "https://kalamazoo.craigslist.org/search/",
    "lansing": "https://lansing.craigslist.org/search/",
    "muskegon": "https://muskegon.craigslist.org/search/",
    "northern michigan": "https://nmi.craigslist.org/search/",
    "port huron": "https://porthuron.craigslist.org/search/",
    "saginaw-midland-baycity": "https://saginaw.craigslist.org/search/",
    "southwest michigan": "https://swmi.craigslist.org/search/",
    "the thumb": "https://thumb.craigslist.org/search/",
    "upper peninsula": "https://up.craigslist.org/search/",
    "bemidji": "https://bemidji.craigslist.org/search/",
    "brainerd": "https://brainerd.craigslist.org/search/",
    "duluth / superior": "https://duluth.craigslist.org/search/",
    "mankato": "https://mankato.craigslist.org/search/",
    "minneapolis / st paul": "https://minneapolis.craigslist.org/search/",
    "rochester": "https://rochester.craigslist.org/search/",
    "southwest MN": "https://marshall.craigslist.org/search/",
    "st cloud": "https://stcloud.craigslist.org/search/",
    "gulfport / biloxi": "https://gulfport.craigslist.org/search/",
    "hattiesburg": "https://hattiesburg.craigslist.org/search/",
    "meridian": "https://meridian.craigslist.org/search/",
    "north mississippi": "https://northmiss.craigslist.org/search/",
    "southwest MS": "https://natchez.craigslist.org/search/",
    "columbia / jeff city": "https://columbiamo.craigslist.org/search/",
    "joplin": "https://joplin.craigslist.org/search/",
    "kansas city": "https://kansascity.craigslist.org/search/",
    "kirksville": "https://kirksville.craigslist.org/search/",
    "lake of the ozarks": "https://loz.craigslist.org/search/",
    "southeast missouri": "https://semo.craigslist.org/search/",
    "st joseph": "https://stjoseph.craigslist.org/search/",
    "st louis": "https://stlouis.craigslist.org/search/",
    "billings": "https://billings.craigslist.org/search/",
    "bozeman": "https://bozeman.craigslist.org/search/",
    "butte": "https://butte.craigslist.org/search/",
    "great falls": "https://greatfalls.craigslist.org/search/",
    "helena": "https://helena.craigslist.org/search/",
    "kalispell": "https://kalispell.craigslist.org/search/",
    "missoula": "https://missoula.craigslist.org/search/",
    "eastern montana": "https://montana.craigslist.org/search/",
    "grand island": "https://grandisland.craigslist.org/search/",
    "lincoln": "https://lincoln.craigslist.org/search/",
    "north platte": "https://northplatte.craigslist.org/search/",
    "omaha / council bluffs": "https://omaha.craigslist.org/search/",
    "scottsbluff / panhandle": "https://scottsbluff.craigslist.org/search/",
    "elko": "https://elko.craigslist.org/search/",
    "las vegas": "https://lasvegas.craigslist.org/search/",
    "reno / tahoe": "https://reno.craigslist.org/search/",
    "new hampshire": "https://nh.craigslist.org/search/",
    "central NJ": "https://cnj.craigslist.org/search/",
    "jersey shore": "https://jerseyshore.craigslist.org/search/",
    "north jersey": "https://newjersey.craigslist.org/search/",
    "south jersey": "https://southjersey.craigslist.org/search/",
    "albuquerque": "https://albuquerque.craigslist.org/search/",
    "clovis / portales": "https://clovis.craigslist.org/search/",
    "farmington": "https://farmington.craigslist.org/search/",
    "las cruces": "https://lascruces.craigslist.org/search/",
    "roswell / carlsbad": "https://roswell.craigslist.org/search/",
    "santa fe / taos": "https://santafe.craigslist.org/search/",
    "binghamton": "https://binghamton.craigslist.org/search/",
    "buffalo": "https://buffalo.craigslist.org/search/",
    "catskills": "https://catskills.craigslist.org/search/",
    "chautauqua": "https://chautauqua.craigslist.org/search/",
    "elmira-corning": "https://elmira.craigslist.org/search/",
    "finger lakes": "https://fingerlakes.craigslist.org/search/",
    "glens falls": "https://glensfalls.craigslist.org/search/",
    "hudson valley": "https://hudsonvalley.craigslist.org/search/",
    "ithaca": "https://ithaca.craigslist.org/search/",
    "long island": "https://longisland.craigslist.org/search/",
    "new york city": "https://newyork.craigslist.org/search/",
    "oneonta": "https://oneonta.craigslist.org/search/",
    "plattsburgh-adirondacks": "https://plattsburgh.craigslist.org/search/",
    "potsdam-canton-massena": "https://potsdam.craigslist.org/search/",
    "syracuse": "https://syracuse.craigslist.org/search/",
    "twin tiers NY/PA": "https://twintiers.craigslist.org/search/",
    "utica-rome-oneida": "https://utica.craigslist.org/search/",
    "watertown": "https://watertown.craigslist.org/search/",
    "asheville": "https://asheville.craigslist.org/search/",
    "boone": "https://boone.craigslist.org/search/",
    "charlotte": "https://charlotte.craigslist.org/search/",
    "eastern NC": "https://eastnc.craigslist.org/search/",
    "greensboro": "https://greensboro.craigslist.org/search/",
    "hickory / lenoir": "https://hickory.craigslist.org/search/",
    "outer banks": "https://outerbanks.craigslist.org/search/",
    "raleigh / durham / CH": "https://raleigh.craigslist.org/search/",
    "wilmington": "https://wilmington.craigslist.org/search/",
    "winston-salem": "https://winstonsalem.craigslist.org/search/",
    "bismarck": "https://bismarck.craigslist.org/search/",
    "fargo / moorhead": "https://fargo.craigslist.org/search/",
    "grand forks": "https://grandforks.craigslist.org/search/",
    "north dakota": "https://nd.craigslist.org/search/",
    "akron / canton": "https://akroncanton.craigslist.org/search/",
    "ashtabula": "https://ashtabula.craigslist.org/search/",
    "chillicothe": "https://chillicothe.craigslist.org/search/",
    "cincinnati": "https://cincinnati.craigslist.org/search/",
    "cleveland": "https://cleveland.craigslist.org/search/",
    "dayton / springfield": "https://dayton.craigslist.org/search/",
    "lima / findlay": "https://limaohio.craigslist.org/search/",
    "mansfield": "https://mansfield.craigslist.org/search/",
    "sandusky": "https://sandusky.craigslist.org/search/",
    "toledo": "https://toledo.craigslist.org/search/",
    "tuscarawas co": "https://tuscarawas.craigslist.org/search/",
    "youngstown": "https://youngstown.craigslist.org/search/",
    "zanesville / cambridge": "https://zanesville.craigslist.org/search/",
    "lawton": "https://lawton.craigslist.org/search/",
    "northwest OK": "https://enid.craigslist.org/search/",
    "oklahoma city": "https://oklahomacity.craigslist.org/search/",
    "stillwater": "https://stillwater.craigslist.org/search/",
    "tulsa": "https://tulsa.craigslist.org/search/",
    "bend": "https://bend.craigslist.org/search/",
    "corvallis/albany": "https://corvallis.craigslist.org/search/",
    "east oregon": "https://eastoregon.craigslist.org/search/",
    "eugene": "https://eugene.craigslist.org/search/",
    "klamath falls": "https://klamath.craigslist.org/search/",
    "medford-ashland": "https://medford.craigslist.org/search/",
    "oregon coast": "https://oregoncoast.craigslist.org/search/",
    "portland": "https://portland.craigslist.org/search/",
    "roseburg": "https://roseburg.craigslist.org/search/",
    "salem": "https://salem.craigslist.org/search/",
    "altoona-johnstown": "https://altoona.craigslist.org/search/",
    "cumberland valley": "https://chambersburg.craigslist.org/search/",
    "erie": "https://erie.craigslist.org/search/",
    "harrisburg": "https://harrisburg.craigslist.org/search/",
    "lancaster": "https://lancaster.craigslist.org/search/",
    "lehigh valley": "https://allentown.craigslist.org/search/",
    "meadville": "https://meadville.craigslist.org/search/",
    "philadelphia": "https://philadelphia.craigslist.org/search/",
    "pittsburgh": "https://pittsburgh.craigslist.org/search/",
    "poconos": "https://poconos.craigslist.org/search/",
    "reading": "https://reading.craigslist.org/search/",
    "scranton / wilkes-barre": "https://scranton.craigslist.org/search/",
    "state college": "https://pennstate.craigslist.org/search/",
    "williamsport": "https://williamsport.craigslist.org/search/",
    "york": "https://york.craigslist.org/search/",
    "rhode island": "https://providence.craigslist.org/search/",
    "charleston": "https://charlestonwv.craigslist.org/search/",
    "columbia": "https://columbia.craigslist.org/search/",
    "florence": "https://florencesc.craigslist.org/search/",
    "greenville / upstate": "https://greenville.craigslist.org/search/",
    "hilton head": "https://hiltonhead.craigslist.org/search/",
    "myrtle beach": "https://myrtlebeach.craigslist.org/search/",
    "northeast SD": "https://nesd.craigslist.org/search/",
    "pierre / central SD": "https://csd.craigslist.org/search/",
    "rapid city / west SD": "https://rapidcity.craigslist.org/search/",
    "sioux falls / SE SD": "https://siouxfalls.craigslist.org/search/",
    "south dakota": "https://sd.craigslist.org/search/",
    "chattanooga": "https://chattanooga.craigslist.org/search/",
    "clarksville": "https://clarksville.craigslist.org/search/",
    "cookeville": "https://cookeville.craigslist.org/search/",
    "knoxville": "https://knoxville.craigslist.org/search/",
    "memphis": "https://memphis.craigslist.org/search/",
    "nashville": "https://nashville.craigslist.org/search/",
    "tri-cities": "https://tricities.craigslist.org/search/",
    "abilene": "https://abilene.craigslist.org/search/",
    "amarillo": "https://amarillo.craigslist.org/search/",
    "austin": "https://austin.craigslist.org/search/",
    "beaumont / port arthur": "https://beaumont.craigslist.org/search/",
    "brownsville": "https://brownsville.craigslist.org/search/",
    "college station": "https://collegestation.craigslist.org/search/",
    "corpus christi": "https://corpuschristi.craigslist.org/search/",
    "dallas / fort worth": "https://dallas.craigslist.org/search/",
    "deep east texas": "https://nacogdoches.craigslist.org/search/",
    "del rio / eagle pass": "https://delrio.craigslist.org/search/",
    "el paso": "https://elpaso.craigslist.org/search/",
    "galveston": "https://galveston.craigslist.org/search/",
    "houston": "https://houston.craigslist.org/search/",
    "killeen / temple / ft hood": "https://killeen.craigslist.org/search/",
    "laredo": "https://laredo.craigslist.org/search/",
    "lubbock": "https://lubbock.craigslist.org/search/",
    "mcallen / edinburg": "https://mcallen.craigslist.org/search/",
    "odessa / midland": "https://odessa.craigslist.org/search/",
    "san angelo": "https://sanangelo.craigslist.org/search/",
    "san antonio": "https://sanantonio.craigslist.org/search/",
    "san marcos": "https://sanmarcos.craigslist.org/search/",
    "southwest TX": "https://bigbend.craigslist.org/search/",
    "texoma": "https://texoma.craigslist.org/search/",
    "tyler / east TX": "https://easttexas.craigslist.org/search/",
    "victoria": "https://victoria.craigslist.ca",
    "waco": "https://waco.craigslist.org/search/",
    "wichita falls": "https://wichitafalls.craigslist.org/search/",
    "logan": "https://logan.craigslist.org/search/",
    "ogden-clearfield": "https://ogden.craigslist.org/search/",
    "provo / orem": "https://provo.craigslist.org/search/",
    "salt lake city": "https://saltlakecity.craigslist.org/search/",
    "st gorg/search/e": "https://stgorg/search/e.craigslist.org/search/",
    "vermont": "https://vermont.craigslist.org/search/",
    "charlottesville": "https://charlottesville.craigslist.org/search/",
    "danville": "https://danville.craigslist.org/search/",
    "fredericksburg": "https://fredericksburg.craigslist.org/search/",
    "hampton roads": "https://norfolk.craigslist.org/search/",
    "harrisonburg": "https://harrisonburg.craigslist.org/search/",
    "lynchburg": "https://lynchburg.craigslist.org/search/",
    "new river valley": "https://blacksburg.craigslist.org/search/",
    "roanoke": "https://roanoke.craigslist.org/search/",
    "southwest VA": "https://swva.craigslist.org/search/",
    "winchester": "https://winchester.craigslist.org/search/",
    "bellingham": "https://bellingham.craigslist.org/search/",
    "kennewick-pasco-richland": "https://kpr.craigslist.org/search/",
    "moses lake": "https://moseslake.craigslist.org/search/",
    "olympic peninsula": "https://olympic.craigslist.org/search/",
    "pullman / moscow": "https://pullman.craigslist.org/search/",
    "seattle-tacoma": "https://seattle.craigslist.org/search/",
    "skagit / island / SJI": "https://skagit.craigslist.org/search/",
    "spokane / coeur d'alene": "https://spokane.craigslist.org/search/",
    "wenatchee": "https://wenatchee.craigslist.org/search/",
    "yakima": "https://yakima.craigslist.org/search/",
    "eastern panhandle": "https://martinsburg.craigslist.org/search/",
    "huntington-ashland": "https://huntington.craigslist.org/search/",
    "org/search/antown": "https://org/search/antown.craigslist.org/search/",
    "northern panhandle": "https://wheeling.craigslist.org/search/",
    "parkersburg-marietta": "https://parkersburg.craigslist.org/search/",
    "southern WV": "https://swv.craigslist.org/search/",
    "west virginia (old)": "https://wv.craigslist.org/search/",
    "appleton-oshkosh-FDL": "https://appleton.craigslist.org/search/",
    "eau claire": "https://eauclaire.craigslist.org/search/",
    "green bay": "https://greenbay.craigslist.org/search/",
    "janesville": "https://janesville.craigslist.org/search/",
    "kenosha-racine": "https://racine.craigslist.org/search/",
    "la crosse": "https://lacrosse.craigslist.org/search/",
    "madison": "https://madison.craigslist.org/search/",
    "milwaukee": "https://milwaukee.craigslist.org/search/",
    "northern WI": "https://northernwi.craigslist.org/search/",
    "sheboygan": "https://sheboygan.craigslist.org/search/",
    "wausau": "https://wausau.craigslist.org/search/",
    "wyoming": "https://wyoming.craigslist.org/search/",
    "guam-micronesia": "https://micronesia.craigslist.org/search/",
    "puerto rico": "https://puertorico.craigslist.org/search/",
    "U.S. virgin islands": "https://virgin.craigslist.org/search/",
    "calgary": "https://calgary.craigslist.ca",
    "edmonton": "https://edmonton.craigslist.ca",
    "ft mcmurray": "https://ftmcmurray.craigslist.ca",
    "lethbridge": "https://lethbridge.craigslist.ca",
    "medicine hat": "https://hat.craigslist.ca",
    "peace river country": "https://peace.craigslist.ca",
    "red deer": "https://reddeer.craigslist.ca",
    "cariboo": "https://cariboo.craigslist.ca",
    "comox valley": "https://comoxvalley.craigslist.ca",
    "fraser valley": "https://abbotsford.craigslist.ca",
    "kamloops": "https://kamloops.craigslist.ca",
    "kelowna / okanagan": "https://kelowna.craigslist.ca",
    "kootenays": "https://kootenays.craigslist.ca",
    "nanaimo": "https://nanaimo.craigslist.ca",
    "prince gorg/search/e": "https://princegorg/search/e.craigslist.ca",
    "skeena-bulkley": "https://skeena.craigslist.ca",
    "sunshine coast": "https://sunshine.craigslist.ca",
    "vancouver": "https://vancouver.craigslist.ca",
    "whistler": "https://whistler.craigslist.ca",
    "winnipeg": "https://winnipeg.craigslist.ca",
    "new brunswick": "https://newbrunswick.craigslist.ca",
    "st john's": "https://newfoundland.craigslist.ca",
    "territories": "https://territories.craigslist.ca",
    "yellowknife": "https://yellowknife.craigslist.ca",
    "halifax": "https://halifax.craigslist.ca",
    "barrie": "https://barrie.craigslist.ca",
    "belleville": "https://belleville.craigslist.ca",
    "brantford-woodstock": "https://brantford.craigslist.ca",
    "chatham-kent": "https://chatham.craigslist.ca",
    "cornwall": "https://cornwall.craigslist.ca",
    "guelph": "https://guelph.craigslist.ca",
    "hamilton-burlington": "https://hamilton.craigslist.ca",
    "kingston": "https://kingston.craigslist.ca",
    "kitchener-waterloo-cambridge": "https://kitchener.craigslist.ca",
    "london": "https://london.craigslist.co.uk",
    "niagara region": "https://niagara.craigslist.ca",
    "ottawa-hull-gatineau": "https://ottawa.craigslist.ca",
    "owen sound": "https://owensound.craigslist.ca",
    "peterborough": "https://peterborough.craigslist.ca",
    "sarnia": "https://sarnia.craigslist.ca",
    "sault ste marie": "https://soo.craigslist.ca",
    "sudbury": "https://sudbury.craigslist.ca",
    "thunder bay": "https://thunderbay.craigslist.ca",
    "toronto": "https://toronto.craigslist.ca",
    "windsor": "https://windsor.craigslist.ca",
    "prince edward island": "https://pei.craigslist.ca",
    "montreal": "https://montreal.craigslist.ca",
    "quebec city": "https://quebec.craigslist.ca",
    "saguenay": "https://saguenay.craigslist.ca",
    "sherbrooke": "https://sherbrooke.craigslist.ca",
    "trois-rivieres": "https://troisrivieres.craigslist.ca",
    "regina": "https://regina.craigslist.ca",
    "saskatoon": "https://saskatoon.craigslist.ca",
    "whitehorse": "https://whitehorse.craigslist.ca",
    "vienna": "https://vienna.craigslist.at",
    "belgium": "https://brussels.craigslist.org/search/",
    "bulgaria": "https://bulgaria.craigslist.org/search/",
    "croatia": "https://zagreb.craigslist.org/search/",
    "prague": "https://prague.craigslist.cz",
    "copenhagen": "https://copenhagen.craigslist.org/search/",
    "finland": "https://helsinki.craigslist.fi",
    "bordeaux": "https://bordeaux.craigslist.org/search/",
    "brittany": "https://rennes.craigslist.org/search/",
    "grenoble": "https://grenoble.craigslist.org/search/",
    "lille": "https://lille.craigslist.org/search/",
    "loire valley": "https://loire.craigslist.org/search/",
    "lyon": "https://lyon.craigslist.org/search/",
    "marseille": "https://marseilles.craigslist.org/search/",
    "montpellier": "https://montpellier.craigslist.org/search/",
    "nice / cote d'azur": "https://cotedazur.craigslist.org/search/",
    "normandy": "https://rouen.craigslist.org/search/",
    "paris": "https://paris.craigslist.org/search/",
    "strasbourg": "https://strasbourg.craigslist.org/search/",
    "toulouse": "https://toulouse.craigslist.org/search/",
    "berlin": "https://berlin.craigslist.de",
    "bremen": "https://bremen.craigslist.de",
    "cologne": "https://cologne.craigslist.de",
    "dresden": "https://dresden.craigslist.de",
    "dusseldorf": "https://dusseldorf.craigslist.de",
    "essen / ruhr": "https://essen.craigslist.de",
    "frankfurt": "https://frankfurt.craigslist.de",
    "hamburg": "https://hamburg.craigslist.de",
    "hannover": "https://hannover.craigslist.de",
    "heidelberg": "https://heidelberg.craigslist.de",
    "kaiserslautern": "https://kaiserslautern.craigslist.de",
    "leipzig": "https://leipzig.craigslist.de",
    "munich": "https://munich.craigslist.de",
    "nuremberg": "https://nuremberg.craigslist.de",
    "stuttgart": "https://stuttgart.craigslist.de",
    "greece": "https://athens.craigslist.gr",
    "budapest": "https://budapest.craigslist.org/search/",
    "reykjavik": "https://reykjavik.craigslist.org/search/",
    "dublin": "https://dublin.craigslist.org/search/",
    "bologna": "https://bologna.craigslist.it",
    "florence / tuscany": "https://florence.craigslist.it",
    "genoa": "https://genoa.craigslist.it",
    "milan": "https://milan.craigslist.it",
    "napoli / campania": "https://naples.craigslist.it",
    "perugia": "https://perugia.craigslist.it",
    "rome": "https://rome.craigslist.it",
    "sardinia": "https://sardinia.craigslist.it",
    "sicilia": "https://sicily.craigslist.it",
    "torino": "https://torino.craigslist.it",
    "venice / veneto": "https://venice.craigslist.it",
    "luxembourg": "https://luxembourg.craigslist.org/search/",
    "amsterdam / randstad": "https://amsterdam.craigslist.org/search/",
    "norway": "https://oslo.craigslist.org/search/",
    "poland": "https://warsaw.craigslist.pl",
    "faro / algarve": "https://faro.craigslist.pt",
    "lisbon": "https://lisbon.craigslist.pt",
    "porto": "https://porto.craigslist.pt",
    "romania": "https://bucharest.craigslist.org/search/",
    "moscow": "https://moscow.craigslist.org/search/",
    "st petersburg": "https://stpetersburg.craigslist.org/search/",
    "alicante": "https://alicante.craigslist.es",
    "baleares": "https://baleares.craigslist.es",
    "barcelona": "https://barcelona.craigslist.es",
    "bilbao": "https://bilbao.craigslist.es",
    "cadiz": "https://cadiz.craigslist.es",
    "canarias": "https://canarias.craigslist.es",
    "granada": "https://granada.craigslist.es",
    "madrid": "https://madrid.craigslist.es",
    "malaga": "https://malaga.craigslist.es",
    "sevilla": "https://sevilla.craigslist.es",
    "valencia": "https://valencia.craigslist.es",
    "sweden": "https://stockholm.craigslist.se",
    "basel": "https://basel.craigslist.ch",
    "bern": "https://bern.craigslist.ch",
    "geneva": "https://geneva.craigslist.ch",
    "lausanne": "https://lausanne.craigslist.ch",
    "zurich": "https://zurich.craigslist.ch",
    "turkey": "https://istanbul.craigslist.com.tr",
    "ukraine": "https://ukraine.craigslist.org/search/",
    "aberdeen": "https://aberdeen.craigslist.co.uk",
    "bath": "https://bath.craigslist.co.uk",
    "belfast": "https://belfast.craigslist.co.uk",
    "birmingham / west mids": "https://birmingham.craigslist.co.uk",
    "brighton": "https://brighton.craigslist.co.uk",
    "bristol": "https://bristol.craigslist.co.uk",
    "cambridge, UK": "https://cambridge.craigslist.co.uk",
    "cardiff / wales": "https://cardiff.craigslist.co.uk",
    "coventry": "https://coventry.craigslist.co.uk",
    "derby": "https://derby.craigslist.co.uk",
    "devon &amp; cornwall": "https://devon.craigslist.co.uk",
    "dundee": "https://dundee.craigslist.co.uk",
    "east anglia": "https://norwich.craigslist.co.uk",
    "east midlands": "https://eastmids.craigslist.co.uk",
    "edinburgh": "https://edinburgh.craigslist.co.uk",
    "essex": "https://essex.craigslist.co.uk",
    "glasgow": "https://glasgow.craigslist.co.uk",
    "hampshire": "https://hampshire.craigslist.co.uk",
    "kent": "https://kent.craigslist.co.uk",
    "leeds": "https://leeds.craigslist.co.uk",
    "liverpool": "https://liverpool.craigslist.co.uk",
    "manchester": "https://manchester.craigslist.co.uk",
    "newcastle / NE england": "https://newcastle.craigslist.co.uk",
    "nottingham": "https://nottingham.craigslist.co.uk",
    "oxford": "https://oxford.craigslist.co.uk",
    "sheffield": "https://sheffield.craigslist.co.uk",
    "bangladesh": "https://bangladesh.craigslist.org/search/",
    "beijing": "https://beijing.craigslist.com.cn",
    "chengdu": "https://chengdu.craigslist.com.cn",
    "chongqing": "https://chongqing.craigslist.com.cn",
    "dalian": "https://dalian.craigslist.com.cn",
    "guangzhou": "https://guangzhou.craigslist.com.cn",
    "hangzhou": "https://hangzhou.craigslist.com.cn",
    "nanjing": "https://nanjing.craigslist.com.cn",
    "shanghai": "https://shanghai.craigslist.com.cn",
    "shenyang": "https://shenyang.craigslist.com.cn",
    "shenzhen": "https://shenzhen.craigslist.com.cn",
    "wuhan": "https://wuhan.craigslist.com.cn",
    "xi'an": "https://xian.craigslist.com.cn",
    "hong kong": "https://hongkong.craigslist.hk",
    "ahmedabad": "https://ahmedabad.craigslist.co.in",
    "bangalore": "https://bangalore.craigslist.co.in",
    "bhubaneswar": "https://bhubaneswar.craigslist.co.in",
    "chandigarh": "https://chandigarh.craigslist.co.in",
    "chennai (madras)": "https://chennai.craigslist.co.in",
    "delhi": "https://delhi.craigslist.co.in",
    "goa": "https://goa.craigslist.co.in",
    "hyderabad": "https://hyderabad.craigslist.co.in",
    "indore": "https://indore.craigslist.co.in",
    "jaipur": "https://jaipur.craigslist.co.in",
    "kerala": "https://kerala.craigslist.co.in",
    "kolkata (calcutta)": "https://kolkata.craigslist.co.in",
    "lucknow": "https://lucknow.craigslist.co.in",
    "mumbai": "https://mumbai.craigslist.co.in",
    "pune": "https://pune.craigslist.co.in",
    "surat surat": "https://surat.craigslist.co.in",
    "indonesia": "https://jakarta.craigslist.org/search/",
    "iran": "https://tehran.craigslist.org/search/",
    "iraq": "https://baghdad.craigslist.org/search/",
    "haifa": "https://haifa.craigslist.org/search/",
    "jerusalem": "https://jerusalem.craigslist.org/search/",
    "tel aviv": "https://telaviv.craigslist.org/search/",
    "west bank": "https://ramallah.craigslist.org/search/",
    "fukuoka": "https://fukuoka.craigslist.jp",
    "hiroshima": "https://hiroshima.craigslist.jp",
    "nagoya": "https://nagoya.craigslist.jp",
    "okinawa": "https://okinawa.craigslist.jp",
    "osaka-kobe-kyoto": "https://osaka.craigslist.jp",
    "sapporo": "https://sapporo.craigslist.jp",
    "sendai": "https://sendai.craigslist.jp",
    "tokyo": "https://tokyo.craigslist.jp",
    "seoul": "https://seoul.craigslist.co.kr",
    "kuwait": "https://kuwait.craigslist.org/search/",
    "beirut, lebanon": "https://beirut.craigslist.org/search/",
    "malaysia": "https://malaysia.craigslist.org/search/",
    "pakistan": "https://pakistan.craigslist.org/search/",
    "bacolod": "https://bacolod.craigslist.com.ph",
    "bicol region": "https://naga.craigslist.com.ph",
    "cagayan de oro": "https://cdo.craigslist.com.ph",
    "cebu": "https://cebu.craigslist.com.ph",
    "davao city": "https://davaocity.craigslist.com.ph",
    "iloilo": "https://iloilo.craigslist.com.ph",
    "manila": "https://manila.craigslist.com.ph",
    "pampanga": "https://pampanga.craigslist.com.ph",
    "zamboanga": "https://zamboanga.craigslist.com.ph",
    "singapore": "https://singapore.craigslist.com.sg",
    "taiwan": "https://taipei.craigslist.com.tw",
    "thailand": "https://bangkok.craigslist.co.th",
    "united arab emirates": "https://dubai.craigslist.org/search/",
    "vietnam": "https://vietnam.craigslist.org/search/",
    "adelaide": "https://adelaide.craigslist.com.au",
    "brisbane": "https://brisbane.craigslist.com.au",
    "cairns": "https://cairns.craigslist.com.au",
    "canberra": "https://canberra.craigslist.com.au",
    "darwin": "https://darwin.craigslist.com.au",
    "gold coast": "https://goldcoast.craigslist.com.au",
    "melbourne": "https://melbourne.craigslist.com.au",
    "newcastle, NSW": "https://ntl.craigslist.com.au",
    "perth": "https://perth.craigslist.com.au",
    "sydney": "https://sydney.craigslist.com.au",
    "tasmania": "https://hobart.craigslist.com.au",
    "wollongong": "https://wollongong.craigslist.com.au",
    "auckland": "https://auckland.craigslist.org/search/",
    "christchurch": "https://christchurch.craigslist.org/search/",
    "dunedin": "https://dunedin.craigslist.co.nz",
    "wellington": "https://wellington.craigslist.org/search/",
    "buenos aires": "https://buenosaires.craigslist.org/search/",
    "bolivia": "https://lapaz.craigslist.org/search/",
    "belo horizonte": "https://belohorizonte.craigslist.org/search/",
    "brasilia": "https://brasilia.craigslist.org/search/",
    "curitiba": "https://curitiba.craigslist.org/search/",
    "fortaleza": "https://fortaleza.craigslist.org/search/",
    "porto alegre": "https://portoalegre.craigslist.org/search/",
    "recife": "https://recife.craigslist.org/search/",
    "rio de janeiro": "https://rio.craigslist.org/search/",
    "salvador, bahia": "https://salvador.craigslist.org/search/",
    "sao paulo": "https://saopaulo.craigslist.org/search/",
    "caribbean islands": "https://caribbean.craigslist.org/search/",
    "chile": "https://santiago.craigslist.org/search/",
    "colombia": "https://colombia.craigslist.org/search/",
    "costa rica": "https://costarica.craigslist.org/search/",
    "dominican republic": "https://santodomingo.craigslist.org/search/",
    "ecuador": "https://quito.craigslist.org/search/",
    "el salvador": "https://elsalvador.craigslist.org/search/",
    "guatemala": "https://guatemala.craigslist.org/search/",
    "acapulco": "https://acapulco.craigslist.com.mx",
    "baja california sur": "https://bajasur.craigslist.com.mx",
    "chihuahua": "https://chihuahua.craigslist.com.mx",
    "ciudad juarez": "https://juarez.craigslist.com.mx",
    "guadalajara": "https://guadalajara.craigslist.com.mx",
    "guanajuato": "https://guanajuato.craigslist.com.mx",
    "hermosillo": "https://hermosillo.craigslist.com.mx",
    "mazatlan": "https://mazatlan.craigslist.com.mx",
    "mexico city": "https://mexicocity.craigslist.com.mx",
    "monterrey": "https://monterrey.craigslist.com.mx",
    "oaxaca": "https://oaxaca.craigslist.com.mx",
    "puebla": "https://puebla.craigslist.com.mx",
    "puerto vallarta": "https://pv.craigslist.com.mx",
    "tijuana": "https://tijuana.craigslist.com.mx",
    "veracruz": "https://veracruz.craigslist.com.mx",
    "yucatan": "https://yucatan.craigslist.com.mx",
    "nicaragua": "https://managua.craigslist.org/search/",
    "panama": "https://panama.craigslist.org/search/",
    "peru": "https://lima.craigslist.org/search/",
    "montevideo": "https://montevideo.craigslist.org/search/",
    "venezuela": "https://caracas.craigslist.org/search/",
    "virgin islands": "https://virgin.craigslist.org/search/",
    "egypt": "https://cairo.craigslist.org/search/",
    "ethiopia": "https://addisababa.craigslist.org/search/",
    "ghana": "https://accra.craigslist.org/search/",
    "kenya": "https://kenya.craigslist.org/search/",
    "morocco": "https://casablanca.craigslist.org/search/",
    "cape town": "https://capetown.craigslist.co.za",
    "durban": "https://durban.craigslist.co.za",
    "johannesburg": "https://johannesburg.craigslist.co.za",
    "pretoria": "https://pretoria.craigslist.co.za",
    "tunisia": "https://tunis.craigslist.org/search/",
}

MOTO_SELLER = {
    'dealer': 'mcd',
    'owner': 'mco',
    'all': 'mca'
}

CAR_SELLER = {
    'dealer': 'ctd',
    'owner': 'cto',
    'all': 'cta'
}

BOOL_OPTIONS = {
    'titles_only': 'srchType=T',
    'has_images': 'hasPic=1',
    'posted_today': 'postToday=1',
    'crypto_okay': 'crypto_currency_ok=1',
    'nearby_areas': 'searchNearby=1'}

PRETTY_BOOL = {
    'titles_only': 'Search titles only',
    'has_images': 'Search must have images',
    'posted_today': 'Only search for items posted today',
    'crypto_okay': 'Cryptocurrency is okay',
    'nearby_areas': 'Include nearby areas'}

PRETTY_RADIO = {
    'auto_title_status=1': 'Title: Clean',
    'auto_title_status=2': 'Title: Salvage',
    'auto_title_status=3': 'Title: Rebuilt',
    'auto_title_status=4': 'Title: Parts only',
    'auto_title_status=5': 'Title: Lien',
    'auto_title_status=6': 'Title: Missing title',
    'condition=10': 'Condition: New',
    'condition=20': 'Condition: Like new',
    'condition=30': 'Condition: Excellent',
    'condition=40': 'Condition: Good',
    'condition=50': 'Condition: Fair',
    'condition=60': 'Condition: Salvage',
    'auto_fuel_type=1': 'Fuel: Gas',
    'auto_fuel_type=2': 'Fuel: Diesel',
    'auto_fuel_type=3': 'Fuel: Hybrid',
    'auto_fuel_type=4': 'Fuel: Electric',
    'auto_fuel_type=6': 'Fuel: Other',
    'auto_paint=1': 'Color: Black',
    'auto_paint=2': 'Color: Blue',
    'auto_paint=20': 'Color: Brown',
    'auto_paint=3': 'Color: Green',
    'auto_paint=4': 'Color: Grey',
    'auto_paint=5': 'Color: Orange',
    'auto_paint=6': 'Color: Purple',
    'auto_paint=7': 'Color: Red',
    'auto_paint=8': 'Color: Silver',
    'auto_paint=9': 'Color: White',
    'auto_paint=10': 'Color: Yellow',
    'auto_paint=11': 'Color: Other',
    'auto_transmission=1': 'Transmission: Manual',
    'auto_transmission=2': 'Transmission: Automatic',
    'auto_transmission=3': 'Transmission: Other',
    'auto_cylinders=1': 'Cylinders: 3',
    'auto_cylinders=2': 'Cylinders: 4',
    'auto_cylinders=3': 'Cylinders: 5',
    'auto_cylinders=4': 'Cylinders: 6',
    'auto_cylinders=5': 'Cylinders: 8',
    'auto_cylinders=6': 'Cylinders: 10',
    'auto_cylinders=7': 'Cylinders: 12',
    'auto_cylinders=8': 'Cylinders: Other',
    'auto_drivetrain=1': 'Drive: FWD',
    'auto_drivetrain=2': 'Drive: RWD',
    'auto_drivetrain=3': 'Drive: 4WD',
    'auto_size=1': 'Size: Compact',
    'auto_size=2': 'Size: Full-size',
    'auto_size=3': 'Size: Mid-size',
    'auto_size=4': 'Size: Sub-compact',
    'auto_bodytype=1': 'Type: Bus',
    'auto_bodytype=2': 'Type: Convertible',
    'auto_bodytype=3': 'Type: Coupe',
    'auto_bodytype=4': 'Type: Hatchback',
    'auto_bodytype=5': 'Type: Mini-van',
    'auto_bodytype=6': 'Type: Offroad',
    'auto_bodytype=7': 'Type: Pickup',
    'auto_bodytype=8': 'Type: Sedan',
    'auto_bodytype=9': 'Type: Truck',
    'auto_bodytype=10': 'Type: SUV',
    'auto_bodytype=11': 'Type: Wagon',
    'auto_bodytype=12': 'Type: Van',
    'auto_bodytype=13': 'Type: Other'}

PRETTY_STRING = {
    'auto_make_model': 'Make & model: ',
    'postal': 'Postal code: ',
    'search_distance': 'Search distance: ',
    'min_auto_year': 'Min year: ',
    'max_auto_year': 'Max year: ',
    'min_auto_miles': 'Min miles: ',
    'max_auto_miles': 'Max miles: ',
    'min_price': 'Min price: ',
    'max_price': 'Max price: '}

